### ISSUE TITLE
catalog_apply() works or returns errors depending on buffer and tiling_size (catalog_options) 

### ISSUE THREAD

**Issue by jequihua** [Jean-Romain/lidR#119]
I'm trying to calculate grid_tincanopy() on a large set of .las files using catalog_apply().

I have not been able to achieve this because no matter what buffer and tiling size I choose I get the following error:

> Error : Number of points is not greater than the number of dimensions.

I built a reproducible example to replicate the error, you will see that first you will get an

> Error : First argument should be a real matrix. (buffer=100, tiling size=900)

Then the
 
> Error : Number of points is not greater than the number of dimensions.

For several values of buffer and tiling_size and finally at buffer=600 and tiling_size=9000 the process finalizes correctly.

Is there anyway to know what rationale (buffer/tiling sizes) there is to a successful process? I have not found any values that will allow me to process my whole dataset yet.

[data](https://www.dropbox.com/sh/6k6uupjak5x3bu0/AAArnHuI0QkGRbxe9hQOBVkqa?dl=0)

---------------------------

```r
# load packages
library("raster")
library("lidR")

# create a catalog
ctg = catalog("./",recursive=TRUE)

# basic function to be applied on each las (create terrain model)
myAnalyze <- function(las) 
{
  # normalize 
  lasnormalize(las, method = "delaunay")
  
  chm = grid_tincanopy(las,90, c(10,15,30), c(0,1) , subcircle = 0.5)

  return(chm)
}

for (i in c(900,1200,9000))
{
  
  print(paste0("tiling_size= ",toString(i)))
  
  for (j in c(100,600))
  {
    print(paste0("buffer= ",toString(j)))
    
    # set catalog options
    catalog_options(buffer = j, multicore = 8, tiling_size = i)
    
    # try to calculate chm on whole dataset using catalog_apply
    output <- try(catalog_apply(ctg, myAnalyze))
  }
}
```

**Comment by Jean-Romain** [comment]
> Error : Number of points is not greater than the number of dimensions.

> Error : First argument should be a real matrix.

These is are errors from the `geometry` package. In the dataset you send to me you have roughly 0.01 points/m². Your parameters for `grid_canopy` are far far to be in adequation with this point density.

I question the need to compute a chm from such dataset with the Krosvavipour algorithm. But well, your analysis your choice. This parameter set starts to looks good.

```r
ctg = catalog("~/Download/issue 119/", recursive=TRUE)

plot(ctg)

las = readLAS(ctg)
lasnormalize(las, method = "delaunay")

plot(las)

chm = grid_tincanopy(las, 90, c(0, 5,10, 20), c(0,100))

plot(chm)
```
