### ISSUE TITLE
Clipping height in point cloud

### ISSUE THREAD

**Issue by Selenachav** [Jean-Romain/lidR#127]
Hello,

This is more of a question than an issue.
I was wondering what function I would use in order to plot a point cloud with a specific height.
I am trying to plot only the first 3 meters of the point cloud/ LAS file I am working with.
any help would be appreciated

**Comment by Jean-Romain** [comment]
The only option is to filter your point cloud to retain a subset below 3 meters. You can do that either in `readLAS()` with the `filter` option or in `lasfilter()`.
