### ISSUE TITLE
coloring lasclassify pointclouds using geotiff

### ISSUE THREAD

**Issue by MichaelBMclean** [Jean-Romain/lidR#131]
I have been following the instructions on the github site, which you provided. I have a question. I am up to the lasclassify section where you have a section on coloring points. 

The first line is slightly different to website but was able to problem solve from notes in R (github)

```r
lidar = readLAS(LASfile, select = "xyz")
```

The next step is the one I'm having trouble with.

```r
RGB = raster::stack("<color.tif>")
```

I have tried changing the color.tif to Megaplot.tif but only end up with a long error message. Does the package have the Megaplot.tiff attached? Like the Megaplot.laz
I couldn't find any information on `raster::stack()`. Does it make a framework for the 3 RGB channels?

**Comment by Jean-Romain** [comment]
The example from the wiki don't necessarily work by copy/paste. This is why the code use the generic string `"<color.tif>"`. In this specific case the  `lidR` package does not come with a geo-referenced RGB image. You can't run this example using only what the package provides.

So you need your own dataset and your own geo-referenced image.

`raster::stack` is a function from the `raster` package. See `?raster::stack`.
