### ISSUE TITLE
Polygones from Point Cloud

### ISSUE THREAD

**Issue by SebastianKasan** [Jean-Romain/lidR#139]
Hello Jean-Romain, 

Can you tell me how to export a polygon file from the Li algorithm? Obviously, the rastertopolygon function does apply here.

Many thanks

Sebastian

**Comment by SebastianKasan** [comment]
You are exactly right. I helped myself now with the ChullLidar2d function from rLiDAR.
Many thanks...

**Comment by Jean-Romain** [comment]
Yes, what you are asking is the `tree_hulls` function that is not avaible yet on CRAN. But you can install the very last version of the package in the `devel` branch from github.

**Comment by Jean-Romain** [comment]
By the way you can problably adapt the code outside the package if you want. https://github.com/Jean-Romain/lidR/blob/devel/R/tree_hulls.r

**Comment by SebastianKasan** [comment]
Thank you very much Jean-Romain, 

could you please send me your email address? I would like to get in touch with you as I am planning to use lidR as a principal component of my master thesis work....
Many thanks...
Sebastian

**Comment by Jean-Romain** [comment]
In R `maintainer("lidR")`.
