### ISSUE TITLE
Hi,how output  the result of grid_terrain as a raster?

### ISSUE THREAD

**Issue by little-pigbear** [Jean-Romain/lidR#141]
Thank you for your lidR,it's amazing.

**Comment by bi0m3trics** [comment]
I have to ask... did you coerce the output to a raster before you saved it? e.g., 
`dtm<-as.raster(dtm)`
and then you'll have to assign the crs e.g., 
`raster::crs(dtm) <- project@crs`
and then
`writeRaster(dtm, filename="path to file.tif", format="GTiff")`

**Comment by Jean-Romain** [comment]
Thanks again @bi0m3trics
