### ISSUE TITLE
Passing LAScatalog to grid_hexametrics

### ISSUE THREAD

**Issue by enjoimore** [Jean-Romain/lidR#145]
Hi, With the updated grid_catalog function, the grid_* functions will accept LAScatalog files with the exception of grid_hexametrics. Is it possible to pass a LAScatalog item to grid_hexametrics using the grid_catalog function? Thanks!

**Comment by Jean-Romain** [comment]
Hi, It isn't possible yet and to be honest I'm not going work on it. I have to redesign `grid_hexametrics` first. Sorry :disappointed:

**Comment by enjoimore** [comment]
Aw bummer, but that is understandable. Keep up the good work! Thanks!
