### ISSUE TITLE
Discrepancy in help for lasclip

### ISSUE THREAD

**Issue by biometrica** [Jean-Romain/lidR#150]
The help file for lasclip indicates: geometry = a geometric object. Currently Polygon and SpatialPolygonsDataFrame from sp are supported and x = An object of class LAS or LAScatalog.  

However, when I input a polygon with class:

```
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"
```

As follows

```r
  # Clip to extent
  las = lasclip(x = prj, geometry = stand )
```

Where, prj is a catalog with class:

```
[1] "LAScatalog"
attr(,"package")
[1] "lidR
```

The following error is produced:

> Error: 'SpatialPolygonsDataFrame' is not supported for 'LAScatalog' objects

**Comment by Jean-Romain** [comment]
Hi

The documentation is pretty clear on that subject:

> Minor differences exist between the LAS and LAScatalog version of lasclip. For example the user can clip a SpatialPolygonsDataFrame from a LAS object but not from a LAScatalog. Also the option inside = FALSE is disabled for LAScatalog objects. These differences are generally justified by memory safety concerns.

You can't clip a `SpatialPolygonDataFrame` from a `LAScatalog`.  There are several reasons for that. Some of them can be found is this thread: https://gis.stackexchange.com/questions/280511/clipping-object-of-class-las-with-polygon-shapefile-using-lidr

**Comment by biometrica** [comment]
Thanks for clarifying that for me, Jean-Romain.  I've found the package to be very useful.  It would be nice if a workshop or webinar were offered at some point for new users.

**Comment by Jean-Romain** [comment]
Please invite me for a workshop and I will be glad to come :wink:
