### ISSUE TITLE
Specify tile alignment in catalog_reshape

### ISSUE THREAD

**Issue by jmmonnet** [Jean-Romain/lidR#151]
Hi,
When reshaping a group of las/laz tiles, I think it will be useful to be able to specify the start point of the grid (similarly to "start" argument in grid_metrics) so that one can make sure that tiles are aligned with other data sets (e.g. images), and also to avoid border effects when processing a single tile.
Thank you !
JM

**Comment by Jean-Romain** [comment]
Hi,

In `lidR v1.6.0`, [`catalog_retile`](https://github.com/Jean-Romain/lidR/wiki/catalog_retile) supersedes `catalog_reshape`.

I just modified how the clusters are aligned. Previously the clusters where (almost) aligned on the left of the `LAScatalog`. This was true for any process implying a `LAScatalog`. They are now aligned on `(0,0)`. This allowed me to add a parameters `alignment` in `catalog_retile`.

I did not tested it extensively. I ran all the unit tests that were already written. Sounds good. Tell me if you find a bug.

That being said, the alignment is available to the user only in `catalog_retile`. In all other `lidR` functions, the modifications I did imply modifications in the alignments but this will not change the outputs obviously and the user never control the alignments (this would be useless by the way).
