### ISSUE TITLE
Implementation of a new ground filtering algorithm

### ISSUE THREAD

**Issue by jianboqi** [Jean-Romain/lidR#153]
Hello Jean-Romain,
   I am recently using your lidR for segmentation of single trees from lidar data. It is very good, and thank you for your nice work. One thing I want to mention is that, I have a ground filtering algorithm, named CSF(https://github.com/jianboqi/CSF), which can handle larger lidar files efficiently. An advantage is that it's parameters are easy to set . It has been implemented in Cloudcompare and also a commercial software (https://www.3dscanninghacks.com/wiki/3DF_Zephyr_Dev_Status_(Avocado) ). I don't know whether it is possible to integate it into lidR. Since I am not very familiar with R, so I don't know this is a easy task or not. The CSF is wrtten in c++. If you are interested, please have a look. 
Thank you very much!
Jianbo Qi

**Comment by Jean-Romain** [comment]
Done https://github.com/Jean-Romain/RCSF. I invited you as a collaborator.
