### ISSUE TITLE
catalog_apply stops with rlas::check_data_vs_header error

### ISSUE THREAD

**Issue by pmagdon** [Jean-Romain/lidR#172]
When using catalog_apply() to run processsing on a catalog of las 1.3 files I get the following error:
Error in rlas::check_data_vs_header(header, data, hard = FALSE) : 
  The header describes extra bytes attributes that are not in the data.

However, when I run the same processing on a single file out of the catalog using readLAS everything is fine. Is there an option to prevent the check or to fix the header?  Is there an option to check which extra byte is causing this problem?

**Comment by Jean-Romain** [comment]
Ok I remember now. Install the lastest available version of `rlas` on CRAN which is `1.2.7`. This should solve your issue.

**Comment by pmagdon** [comment]
Thanks for the quick repons. Yes update of rlas from Cran solves the issue!
