### ISSUE TITLE
Errors in the development version of lidR 2.0.0.  Example of lastrees

### ISSUE THREAD

**Issue by ManuelSpinola** [Jean-Romain/lidR#178]
I am trying the development version of lidR 2.0.0 (windows 10, R 3.5.1) but I found several errors.  This is one:

> LASfile <- system.file("extdata", "MixedConifer.laz", package="lidR")

> las = readLAS(LASfile, select = "xyz", filter = "-drop_z_below 0")

> col =  pastel.colors(200)

> lastrees(las, hamraz2016())
Error in C_hamraz_segmentation(disc, nps, gap_sensitivity, MDCW, epsilon,  : 
  object '_lidR_C_hamraz_segmentation' not found

**Comment by Jean-Romain** [comment]
This is known issue reported several times here. It happens to many Windows users who compile the code themselves.  Some functions are randomly missing. I don't know where does it comes from. When binary are provided by the CRAN it works so I won't try fix it. Anyway it is not reproducible.
