### ISSUE TITLE
How to compute DBH automatically?

### ISSUE THREAD

**Issue by muzo583** [Jean-Romain/lidR#185]
Hi all,

 is there a way for calculation of DBH with lidR?

thanks.

**Comment by Jean-Romain** [comment]
Hi. The lidR package is designed to work with ALS data, a point of view from which the trucks cannot be seen. Thus you will never find an algorithm in lidR to measure the DBH of trees.

**Comment by bi0m3trics** [comment]
Just a quick addition to the comment from @Jean-Romain - Assuming you're talking about getting dbh from Airborne LiDAR data, with a little effort and additional data from sampled tree allometrics and one could use the outputs from `lastrees` to build a model that predicts dbh (relatively well, depending on species) using lidR-derived tree heights, canopy areas., and possibly other `tree_metrics`. If you're talking about TLS, then that's a different matter...

**Comment by Jean-Romain** [comment]
Indeed, if you were talking about allometric relashionship the lidR package contains only "algorithms" no "relashionships"

**Comment by biometrica** [comment]
@bi0m3trics @muzo583 @Jean-Romain I think you will find predicting DBH from ALS using segmentation algorithms of lidR, with precision and accuracy comparable to traditional forest inventory, will be difficult to impossible for achieve for the major commercial forest species in North America (Douglas-fir, Southern pine). I don't doubt you can construct a model with great fit statistics.  Independent validation of the model might produce less promising results.  Before you get to deep into this @muzo583 , I think you'll also want to focus in on stocking (trees per unit area) and species assignment.  Using lidR, I've gotten some reasonable results for the above points of discussion - but there is a lot of work left to do.  @bi0m3trics I think the results you described are reasonable for well spaced ponderosa pine, or longleaf pine, for that matter.

**Comment by biometrica** [comment]
@muzo583 @Jean-Romain @bi0m3trics To be clear, and I am sure Jean-Romain wants it to be clear - fitting equations and estimating forest metrics is the responsibility of the user, not lidR.

**Comment by Jean-Romain** [comment]
@biometrica exactly what I wanted to say :wink:

**Comment by muzo583** [comment]
I would like to learn that if lidR has a direct function. I thought it  may be easy to create a function for circle fit and integrate this to LidR package? is it suitable for lidR?

**Comment by Jean-Romain** [comment]
Circle fit on what kind of data? TLS to fit circle on trucks or ALS to fit circle on crowns. On ALS there is the function `tree_hulls` to compute the crown hulls. The hulls can be convex or concave but not circle fit yet.

```r
las = readLAS(...)
lastrees(las, ...)
spdf = tree_hulls(las)
```

**Comment by Jean-Romain** [comment]
Right, you can manipulate any point cloud within lidR but algorithms are mainly designed for ALS in a forestry context. Within lidR v2.0 you will be able to write you own plugins and thus you will be able to create an algorithm for TLS that can be used in `lastrees`.

**Comment by bi0m3trics** [comment]
@biometrica and to further add to clarity... I was only referring to the allometrics (or relationships) of tree crown area and height to dbh (and I did say it would depend on species - but it should hold well for most conifers, once you have them isolated) and made no mention of "precision and accuracy comparable to traditional forest inventory"... I think people jumping to segmentation and it's applications and/or comparisons and/or promise to "traditional forest inventory" produced by " large corporate timberland organizations" is a user issue and if I learned one thing in my years of software development is that you can produce code that addresses user issues. That's HR's and the user's supervisor's problem.

**Comment by muzo583** [comment]
Thank you, everybody, for all contributions.
Bests.
