### ISSUE TITLE
lasclip sample code

### ISSUE THREAD

**Issue by jesimpson2** [Jean-Romain/lidR#186]
Hi JR, 

Sorry for the newbie question, but I'm a bit stumped. I'm trying to clip a lascatalog with a shapefile of polygons using your code on your site [https://github.com/Jean-Romain/lidR/wiki/lasclip](https://github.com/Jean-Romain/lidR/wiki/lasclip)

The problems comes in creating the filenames, where i has not been defined in the loop, therefore filenames[i] doesn't work. I am not sure how to make the output filename==polygon ID with which the laz file has been clipped. 

Please help! Thanks very much

**Comment by Jean-Romain** [comment]
This example is not mine. Somebody else contributed in the wiki. It is not the best example because it implies a data specific code as you mentioned it. Anyway you can generate filename from an attribute of the shapefile that is used as ID for example.

```r
filenames = paste0("/path/to/exported/folder/filemane_", shapefile$attribute_id, ".las")
```

But this is not a question about `lidR` but a generic question about R.

You can also try the [version 2 of lidR](https://github.com/Jean-Romain/lidR/issues/177) package right now. In that case you can replace the example by:

```r
ctg = catalog(‘path/to/lasfiles’)
shapefile = shapefile("path/to/shapefile.shp")

opt_outputfiles(ctg) <- "‘path/to/exported/folder/filename_{attribute_id}.las"
opt_cores <- 4

new_ctg = lasclip(las, shapefile)
```

**Comment by jesimpson2** [comment]
Thanks for replying so quickly. As for V2, I installed rtools, RCSF and rlas, but how do I update lidR to v2? opt_outputfiles is not a recognised function so I don't think i have it installed..?

Sorry for simple questions,  it would be good to get this working

**Comment by Jean-Romain** [comment]
Find your package version

```r
packageVersion("lidR")
```

Install version pre-release of verison 2.0. I plan to make the release in early 2019. Installing the version 2.0 your become a tester of this new major release.

```r
devtools::install_github("Jean-Romain/lidR", dependencies=TRUE, ref="devel")
```

The function is actually `opt_output_files`

**Comment by jesimpson2** [comment]
Hi again,

I am coming across the following error:

  |=================================================================                                                        |  54%Error in C_reader(ifiles, ofile, select, filter, filter_wkt) :
  Cannot write several files at one time.
In addition: Warning message:
In if (ofile != "") ofile = suppressWarnings(normalizePath(ofile)) :
  the condition has length > 1 and only the first element will be used

When using the following code, outputting the files to the wd:

ctg=catalog(infolder)

opt_output_files(ctg) <- "clip_{GS_shp$gid}"
opt_cores <- 4

new_ctg = lasclip(ctg, GS_shp)

Do you have any suggestions?

**Comment by Jean-Romain** [comment]
Thank you for trying the v2 and for reporting issue. Here it is not a bug but a user error but I should add a test to throw an error earlier. What you meant is:

```r
opt_output_files(ctg) <- "clip_{gid}"
```

The internal engine recognize `gid` as an attribute of the shapefile.

**Comment by Jean-Romain** [comment]
Error handling improved in 8d5853d

**Comment by CharlesCRTE** [comment]
Bonjour!
J'ai tenté d'appliquer votre exemple de code aujourd'hui mais cela n'a pas fonctionné et aucune mention de l'erreur n'a été faite. J'ai tout de même trouvé la solution au problème qui provenait du lancement de la progress bar. En effet, aucune mention qui indiquerait la nécessité d'installer la librairie "progress" n'a été faite dans les détails du code et pourtant cela peut nuire au bon lancement du code dans sa totalité.  Cela serait pourrait être utile de préciser la nécessité de l'installation du package "progress" pour pouvoir lancer ce code correctement ? 
En tout cas, mis à part ce soucis, le code fonctionne parfaitement ! Merci beaucoup !

**Comment by Jean-Romain** [comment]
It should work without `progress`. If not it is a bug. I'll check that.
