### ISSUE TITLE
Plotting a dtm using plot3d function

### ISSUE THREAD

**Issue by Selenachav** [Jean-Romain/lidR#188]
Hello, I'm trying to plot a dtm as a 3d plot using the script below. Before I would just use the plot3d function but it seems it doesn't work anymore any help on how I set up the parameters need to use the plot3d function
> dtm = grid_terrain(lidar1, method = "knnidw", k = 10L, p=2)

> plot3d(dtm)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘yFromRow’ for signature ‘"RasterLayer", "missing"’

**Comment by Jean-Romain** [comment]
Hi, this issue have already been submitted here https://github.com/Jean-Romain/lidR/issues/187. It is related to the latest update of the `raster` package and is not really related to `lidR`. See the other issue for a ready fix.
