### ISSUE TITLE
Could not find function "cluster_write" with 2 cores

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/lidR#193]
There is a potential bug when processing a catalog using more than one core and trying to save results to files with

```r
opt_output_files(ctg) <-"F:\\data\\out\\qc_{XLEFT}_{YBOTTOM}_metrics"`
`opt_cores(ctg) <- 2
```

Results in a error:

```
Error in cluster_write(x, current_processed_cluster@save, output_options) : 
  could not find function "cluster_write"
```

Everything works fine when the number of cores is set to 1.

_Originally posted by @ptompalski in https://github.com/Jean-Romain/lidR/issues/177#issuecomment-440811756_

**Comment by Jean-Romain** [comment]
```r
LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
ctg = catalog(LASfile)

file = paste0(tempdir(), "/file_{XLEFT}_{ID}")

opt_output_files(ctg) = file
opt_cores(ctg) <- 2
opt_chunk_size(ctg) <- 120

# To get the same behavior than on Windows
ctg@processing_options$plan = "future::multisession"

# Working
res = grid_canopy(ctg, 2, p2r())

# Not working
res = grid_metrics(ctg, mean(Z), 10)
```

This issue comes from the manual exportation of the globals. I think it can be fixed with the lastest release of  `future` ([changelog](https://github.com/HenrikBengtsson/future/blob/master/NEWS) bullet one of 1.1.10).  I need to study the new options of future to fix it easily.

**Comment by Jean-Romain** [comment]
Fixed

**Comment by ptompalski** [comment]
works great, thanks JR!
