### ISSUE TITLE
Scientific format for coordinates in output filename

### ISSUE THREAD

**Issue by ptompalski** [Jean-Romain/lidR#194]
A very minor issue:
 
When using opt_output_files(catalog) and {XLEFT} / {YBOTTOM} etc., and for coodinates with many zeroes, the coordinates are formatted as 
eg. 
2e+05_5192000_metrics.tif
instead of 
200000_5192000_metrics.tif

**Comment by Jean-Romain** [comment]
Thank you for reporting. It should be fixed.
