### ISSUE TITLE
lastrees proccessing time

### ISSUE THREAD

**Issue by NatKatUP** [Jean-Romain/lidR#199]
Hi,
I am proccessing photogrammetric point clouds with lidR (great package, thanks a lot!) and run into some problems with the tree segmentation using the lastrees_li2 function. 
My point clouds are very dense, more than 500 points/m^2 and, as mentioned in Li et a., 2012, the processing time increases exponentially with density. I am wondering if there is a way to parallelize the function?

**Comment by Jean-Romain** [comment]
Even if there was a way to parallelize the computation, the runtime time increases exponentially.There is currently no way to compensate an exponential runtime increases. 

One option could be to linearize the algorithm itself with a spatial index. This is feasible and all the tools to do so are available internally but I don't have the time to deeply rewrite the algorithm. You just can't process such amount of points in R.
