### ISSUE TITLE
Error using tree_detection: object not found

### ISSUE THREAD

**Issue by neko1010** [Jean-Romain/lidR#202]
Using lidR version 2.0 and R v3.5.1, I continue to get the following error when trying to use a CHM as the input argument rather than a point cloud. In previous versions, tree_detection could be used on a rasterised CHM, is this still the case in v 2.0? If so, could you help me understand the error returned?

> ttops <- tree_detection(chm, lmf(ws = 2, hmin = 1))
Error in C_lmf(las@data, ws, hmin, circular) : 
  object '_lidR_C_lmf' not found

Unfortunately, the CHM file is too large to attach...

**Comment by Jean-Romain** [comment]
Hi! This question has been asked multiple time actually. See https://github.com/Jean-Romain/lidR/issues/178 for example.

What I suggest you for the moment is to install the package using a binary for windows built by the CRAN. See https://github.com/Jean-Romain/lidR/issues/177 (first post)

I will release the version 2 on Jan 2nd 2019.
