### ISSUE TITLE
Problemas when loading Example.las

### ISSUE THREAD

**Issue by ManuelSpinola** [Jean-Romain/lidR#208]
When running the example for tree segmentation with lidR 2.0.0 it say Example.las is invalid data

> las = lidR::readLAS("Datos/Example.las")
Invalid data: 194244 points with a 'return number' greater than the 'number of returns'.Invalid data: 194244 points with a number of returns equal to 0 found.

**Comment by Jean-Romain** [comment]
https://gis.stackexchange.com/questions/305092/why-a-laz-file-give-warning-about-numbers-of-returns-using-readlas-in-r
