### ISSUE TITLE
Issue with lasnormalize and grid_terrain

### ISSUE THREAD

**Issue by amithaldar87** [Jean-Romain/lidR#211]
`lasc03_norm <- lasnormalize(lasC03, tin())`
Error in UseMethod("lasnormalize", las) : 
  no applicable method for 'lasnormalize' applied to an object of class "c('data.table', 'data.frame')"
 
`dtmc03 <- grid_terrain(lasC03, 0.05, kriging(k=10L))`
Error in UseMethod("grid_canopy", las) : 
  no applicable method for 'grid_canopy' applied to an object of class "c('data.table', 'data.frame')"

**Comment by bi0m3trics** [comment]
You wouldn't happen to be a windows user would you? I tend to get these types of message in windows when packages don't load or load partially (it happens). I wonder if explicitly loading the `data.table` package would resolve the issue? If so, I typically reinstall the broken package (with `dep=TRUE`) or explicitly load faulty package when I see the "`no applicable method`" error, as that usually means R doesn't know what to do with the object it's being passed... and of course it should know.

**Comment by Jean-Romain** [comment]
There is no mystery here, this is just the regular R behavior. You try to feed the function with the wrong object you received a regular R error. The functions expect a `LAS` object no a `data.frame` that's it. If you want to get started with lidR start with the example given in the documentation. Then if you have questions please ask on https://gis.stackexchange.com/. Thanks
