### ISSUE TITLE
Error in grid_terrain with keep_lowest=True

### ISSUE THREAD

**Issue by komazsofi** [Jean-Romain/lidR#213]
I have got an error message during trying to use grid_terrain() function. For me, it is really important to keep the lowest values due to I am trying to avoid to get artifacts due to really step ditches in the rural Netherland landscape. If I set keep_lowest to TRUE I get an error.

```r
las=readLAS("205000_600000_ground.las")
grid_terrain(las, res = 2.5, knnidw(), keep_lowest = TRUE)
```

The error:
```
Error in lazyeval::f_capture(func) : Promise has already been forced
```

**Comment by Jean-Romain** [comment]
That one was easy! Thanks for reporting. It is fixed. I will release lidR 2.0.1 on Feb 22nd but you can install from github.

Also please always try to reproduce error with a dataset given in the package first. It is easier to me. If it does not work with the data provided it is usually an simple error in the code. If it does not work only with your dataset it is likely to be a nasty issue like your other issue.

```r
library(lidR)
LASfile <- system.file("extdata", "Topography.laz", package="lidR")
las = readLAS(LASfile)
grid_terrain(las, res = 2.5, knnidw(), keep_lowest = TRUE)
```
