### ISSUE TITLE
grid_density help file error

### ISSUE THREAD

**Issue by SebastianKasan** [Jean-Romain/lidR#216]
Hello Jean-Romain, 

I tried to open the help menu of the grid_density function in 2.0. Nothing happens and a while later R says:
Error in fetch(key) : 
  lazy-load database 'C:/Users/admin/Documents/R/win-library/3.5/lidR/help/lidR.rdb' is corrupt

Any suggestions?
Many thanks
Sebastian

**Comment by Jean-Romain** [comment]
Try to reinstall and if there error persists [google it](https://www.google.com/search?ei=WNVSXKGRIMW9ggfvgbjwBQ&q=Error+in+fetch%28key%29+%3Alazy-load+database+is+corrupt&oq=Error+in+fetch%28key%29+%3Alazy-load+database+is+corrupt&gs_l=psy-ab.3...0.0..13956...0.0..0.0.0.......0......gws-wiz.SNDJxQHifmg)

**Comment by SebastianKasan** [comment]
Thank you, that has fixed it. It did not come to my mind that this is not a lidR specific problem.. Sorry

 

Von: Jean-Romain [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Januar 2019 12:03
An: Jean-Romain/lidR <lidR@noreply.github.com>
Cc: SebastianKasan <kasanmascheff@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [Jean-Romain/lidR] grid_density help file error (#216)

 

Try to reinstall and if there error persists google it <https://www.google.com/search?ei=WNVSXKGRIMW9ggfvgbjwBQ&q=Error+in+fetch%28key%29+%3Alazy-load+database+is+corrupt&oq=Error+in+fetch%28key%29+%3Alazy-load+database+is+corrupt&gs_l=psy-ab.3...0.0..13956...0.0..0.0.0.......0......gws-wiz.SNDJxQHifmg>
