### ISSUE TITLE
Typo in LAScatalog vignette

### ISSUE THREAD

**Issue by pobsteta** [Jean-Romain/lidR#220]
There is a bug in wiki page, a "s" is not here at opt_output_file"s"(ctg) in [LAScatalog-class vignette](https://cran.r-project.org/web/packages/lidR/vignettes/lidR-LAScatalog-class.html)

```r
opt_output_file(ctg) <- "folder/where/to/store/outputs/{ORIGINALFILENAME}_normalized"
output <- lasnormalize(ctg, tin())
```

**Comment by Jean-Romain** [comment]
Thank you for following the vignettes. Because the package does not include enough data, the code of the vignette is not tested and consequently there are typos. I will fix that.
