### ISSUE TITLE
Typo in LAS-class vignette

### ISSUE THREAD

**Issue by pobsteta** [Jean-Romain/lidR#221]
Hi there is an space into the formule `- drop_z_above 50` in the [LAS-class vignette](https://cran.r-project.org/web/packages/lidR/vignettes/lidR-LAS-class.html)

```r
las = readLAS("file", filter = "-keep_first")
las = readLAS("file", select = "xyzi", filter = "-keep_first -drop_z_below 5 - drop_z_above 50")
```

**Comment by Jean-Romain** [comment]
Thank you I will fix it
