### ISSUE TITLE
lasflightline not updating data table

### ISSUE THREAD

**Issue by mbedward** [Jean-Romain/lidR#225]
In lidR version 2.0.1 lasflightline simply fills the flightlineID column of the data table with ones. The problem seems to be that a local variable 'gpstime' (set to NULL) is passed to function .lagissup instead of the gpstime column of the data table.

https://github.com/Jean-Romain/lidR/blob/2e71c0c9a9852fe16ea8efd38e54a7a729be1ed3/R/lasindentify.r#L88

**Comment by Jean-Romain** [comment]
Thank you for reporting this bug. This was a big one. I completely broke the function between v1.6.1 and v2.0.0.
