### ISSUE TITLE
Setting custom metrics and using Voxels

### ISSUE THREAD

**Issue by Selenachav** [Jean-Romain/lidR#236]
Hello,
I am trying to run some custom metrics in order to transform my lidar data set into voxels so  that I can get a pulse count at my set height intervals

I get a few errors though the "intensity" , "PulseID' and "scan angle can not found. Is there new variables I need for the PulseID and ScanAngle use because of the update? I have attached a copy of my script below which I have not run since 1.5 version of the package has been updated. 

```r
grid_metrics3d(lidar2, length(Z),res = 0.5)
grid_metrics3d(lidar2, mean(ScanAngle),res = 0.5)

myMetrics = function(i, angle, pulseID)
{
  ret = list(
    npulse  = length(unique(pulseID)),
    angle   = mean(angle),
    imean   = mean(i)
  )
  
  return(ret)
}

voxels2 = grid_metrics3d(lidar2, myMetrics(Intensity, ScanAngle, 
                                           pulseID),res = 0.5)
plot (voxels2)

v01 = voxels2[which(voxels2$Z=='0.25')]
v02 = voxels2[which(voxels2$Z=='0.75')]
v03 = voxels2[which(voxels2$Z=='1.25')]
v04 = voxels2[which(voxels2$Z=='1.75')]
v05 = voxels2[which(voxels2$Z=='2.25')]
v06 = voxels2[which(voxels2$Z=='2.75')]
v07 = voxels2[which(voxels2$Z=='3.25')]
v08 = voxels2[which(voxels2$Z=='3.75')]
v09 = voxels2[which(voxels2$Z=='4.25')]
v010 = voxels2[which(voxels2$Z=='4.75')]


vPostPulses = c(colSums(v01)[4],colSums(v02)[4],colSums(v03)[4],colSums(v04)[4],
                colSums(v05)[4],colSums(v06)[4],colSums(v07)[4],colSums(v08) 
                [4],colSums(v09)[4],
                colSums(v010)[4],colSums(v011)[4]
)

VPostCount = c(dim(v01)[1],dim(v02)[1],dim(v03)[1],dim(v04)[1],dim(v05)[1],dim(v06)[1],dim(v07)[1],dim(v08)[1],dim(v09)[1],
               dim(v010)[1])


as.table(vPostPulses)
as.table(VPostCount)
```

**Comment by Jean-Romain** [comment]
Hi,

1. The pulse are no longer computed at read time. Use `laspulse()` to compute the pulse IDs.
2. `ScanAngle` is now `ScanAngleRank` for point formats < 6. `ScanAngle` is reserved for point format >= 6 according to the specifications. This comes from the `rlas` package.

If you have questions please ask on https://gis.stackexchange.com/ and try to only report bugs on github.
