### ISSUE TITLE
Error in grid_canopy

### ISSUE THREAD

**Issue by Eduardo-Tusa** [Jean-Romain/lidR#238]
Hi,
When I use a for loop:

```r
myres = c(1.0,0.95,0.9,0.85,0.8,0.75,0.7,0.65,0.6,0.55,0.5,0.45,0.4,0.35,0.3,0.25)
for (ires in myres)
{
  chm = grid_canopy(las, res = ires, p2r())
  plot(chm)
}
```

I got an error:

```r
Error in algorithm(las, layout) : 
  Internal error: matrix returned at the C++ level does not match with the layout. Please report this bug.
```

But, when I write like this:

```r
chm = grid_canopy(las, res = 0.2, p2r())
```

I have no problem at all...

**Comment by Jean-Romain** [comment]
This error should not happen but it still happens in very rare cases with some specific dataset and resolution. Please find the resolution that failed and share the point cloud or a subset of the point cloud that enable to reproduce. Thanks.

**Comment by Jean-Romain** [comment]
No news ?

**Comment by alekszaf** [comment]
I have encountered the same problem whenever I pick resolution lower than 0.4-0.5, depending on the plot. I have attached two of the plots I am processing, plot C shows the error if res < 0.4, plot E res <0.5.

[hlw_june_plots.zip](https://github.com/Jean-Romain/lidR/files/3468526/hlw_june_plots.zip)

.

**Comment by Jean-Romain** [comment]
Thank you, I identified the issue. I'm working on a fix.

**Comment by Jean-Romain** [comment]
Fixed.
