### ISSUE TITLE
lasfilterdecimate with homogenize not working with use_pulse=TRUE

### ISSUE THREAD

**Issue by melfed** [Jean-Romain/lidR#245]
When I run `lasfilterdecimate` with the homogenize option excluding `use_pulse =TRUE` it works but when I include `use_pulse=TRUE`, it does not work.

IE: The code below does not work 

```r
currenttilethinned <- lasfilterdecimate(currenttilepulse,homogenize(density,res=20,use_pulse = TRUE))
```

The code below works but I am not sure if it is filtering by pulse (`laspulse` has already been run on the input LAS file (`currenttilepulse`)) 

```r
currenttilethinned <- lasfilterdecimate(currenttilepulse,homogenize(4.25,res=20))
```

Does homogenize automatically use the pulses when `pulseID` is present?

**Comment by Jean-Romain** [comment]
Please choose either stackexchange OR github but not both. If you think you found a bug ask here, if you have question about how to use lidR please ask on stackechange. So far, as I said on stackexchange, I can't help you because *it doesn't work* is not a question.
