### ISSUE TITLE
Generating of LAX file possible?

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/lidR#250]
Does lidR allow the creation of LAX files for spatial indexing or do we need to create those from other software (ie: lasindex from LAStools)? If it's not possible within lidR, here is my feature request.

**Comment by Jean-Romain** [comment]
I strongly recommend `lasindex` from `LAStools`. But there is `rlas::writelax` that writes one lax files and that is nothing else than a simplified version of `lasindex` with default parameters. This is also an an internal non documented function `lidR:::catalog_laxindex`. See also [this vignette](https://cran.r-project.org/web/packages/lidR/vignettes/lidR-computation-speed-LAScatalog.html)
