### ISSUE TITLE
Error reading .las data, worked before updates

### ISSUE THREAD

**Issue by garmzy** [Jean-Romain/lidR#256]
I recently updated some packages and I started getting an error when I run this simple code:

> LASfile3 <- ('D:/Courses/kpn/KPN project/cloud.las')
> las3 = lidR::readLAS(LASfile3, select = "*+")

Here is the error.

Error: 'readlasheader' is not an exported object from 'namespace:rlas'

What am I doing wrong?

Thank you!

Cory

**Comment by Jean-Romain** [comment]
You probably updated the `rlas` package but not the `lidR` package. `readlasheader` is function replaced for a long time in `rlas`. You are likely to use a very old version of `lidR`. Please ensure you are using recent version of both `rlas` and `lidR`.

**Comment by garmzy** [comment]
Thank you! This package is such a big help for my PhD research. You rock!!!
