### ISSUE TITLE
catalog_laxindex() won't write when opt_output_files() set on catalog

### ISSUE THREAD

**Issue by lucas-johnson** [Jean-Romain/lidR#279]
I believe this is a bug. Or maybe I should be writing the .lax files to the originally directory? I wonder then, will the new normalized files need to be re-indexed? Thank you for taking a look at this. 

```r
opt_output_files(ctg) <- '/temp/normalized_{ORIGINALFILENAME}'
lidR:::catalog_laxindex(ctg)
#> |=====|   4%
#> Error: Trying to write an object of class numeric but this type is not supported.

opt_output_files(ctg) <- ""
lidR:::catalog_laxindex(ctg)
#> |====================================================================| 100%
```

**Comment by Jean-Romain** [comment]
This is a bug. Not a big one actually. `catalog_index()` writes `lax` file along with the ` las/z` files with the same names than original file names. There is no custom behavior. It should have warned about meaningless options but instead it failed badly.

**Comment by lucas-johnson** [comment]
No worries 👍
