### ISSUE TITLE
Error in lmfauto() : could not find function "lmfauto"

### ISSUE THREAD

**Issue by LucaRom** [Jean-Romain/lidR#291]
Possible small bug. Was testing different things for tree detection and couldn't get lmfauto() to work. 

Here is an example running with the "Example.las" from the Wiki tutorials :

```r
library("lidR")
las = readLAS("Example.las")
tops <- tree_detection(las, lmfauto())
```

Would return :

```r
> tops <- tree_detection(las, lmfauto())
Error in lmfauto() : could not find function "lmfauto"
```

**Comment by Jean-Romain** [comment]
Where have you learned about `lmfauto()`. This is indeed an existing algorithm but is has not been exported to the user. This is something I'm working on and that is in the package for different reason but not for the regular users yet.

**Comment by Jean-Romain** [comment]
I think I got it. There is a work-in-progress documentation and this documentation can be found by users despite the fact it should be an internal documentation only. I will remove the documentation. Sorry for the trouble.

**Comment by LucaRom** [comment]
No problem, I am not sure where I got the documentation!? Thanks for the follow-up.
