### ISSUE TITLE
How to use gridmetrics for linear regression (lm)

### ISSUE THREAD

**Issue by muzo583** [Jean-Romain/lidR#297]
Dear Romain,
 I would like to use `grid_metrics()` function for fitting lm(linear regression) function, as 

```r
pp <- grid_metrics(las, ~lm(Z~X+Y, data = las@data), res=5)
```
but I get an error below,

Error in `[.data.table`(las@data, , if (!anyNA(.BY)) c(eval(call)), by = cells) : 
  All items in j=list(...) should be atomic vectors or lists. If you are trying something like j=list(.SD,newcol=mean(colA)) then use := by group instead (much quicker), or cbind or merge afterwards.

How can I modify this function to lm?

Thanks.

**Comment by Jean-Romain** [comment]
Hi, I no longer answer to questions on github. Please ask your questions on https://gis.stackexchange.com/ with the tag `lidr`. This way your question and the community's answer will benefit to everybody by being indexed by search engine. Please only report bug on github (or feature request). Thanks.
