### ISSUE TITLE
Use some tiles as "buffer only" when processing a LAScatalog

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/lidR#298]
This feature request comes from  [stackexchange](https://gis.stackexchange.com/questions/341631/ignoring-buffer-files-in-processing). When processing a LAScatalog it might be suitable to process only a subset of the LAScatalog but keep the other tiles to ensure to load a buffer everywhere.

**Comment by Jean-Romain** [comment]
lidR 2.2.0 now have this capability. See examples below. As usual, it is the development  version so it might change a bit before the actual release.

``` r
library(lidR)
ctg = readLAScatalog("/mydata/")

# Add an attribute 'processed' to tell which file to actually process
processed <- rep(FALSE, nrow(ctg))
processed[c(7:9, 12:14)] <- TRUE
ctg$processed <- processed

# plot function has been updated to show the files processed/not processed
plot(ctg)
```

![](https://i.imgur.com/dbJY9XO.png)

``` r
# Plot to see if the chunk are correctly computed
opt_chunk_size(ctg) <- 0
plot(ctg, chunk = TRUE)
```

![](https://i.imgur.com/6cHECqk.png)

``` r
opt_chunk_size(ctg) <- 500
plot(ctg, chunk = TRUE)
```

![](https://i.imgur.com/ERXi3qe.png)

``` r
opt_chunk_size(ctg) <- 700
plot(ctg, chunk = TRUE)
```

![](https://i.imgur.com/6DbQxXb.png)

``` r
opt_chunk_size(ctg) <- 500
opt_chunk_alignment(ctg) <- c(75, 75)
plot(ctg, chunk = TRUE)
```

![](https://i.imgur.com/HqZEQvF.png)

``` r
# Because chunks are necessarily rectangular there are some 'imperfect cases'
processed <- rep(FALSE, nrow(ctg))
processed[c(7:9, 13L, 18L)] <- TRUE
ctg$processed <- processed
plot(ctg)
```

![](https://i.imgur.com/gqXcE8u.png)

``` r
opt_chunk_size(ctg) <- 500
plot(ctg, chunk = TRUE)
```

![](https://i.imgur.com/DUY9K0v.png)

``` r
#  Try to process
opt_chunk_size(ctg) <- 0
m = grid_metrics(ctg, ~mean(Z), 20)
plot(m, col = height.colors(50))
```

![](https://i.imgur.com/6OHid6s.png)

The function `catalog_select()` has also been updated to flag some tiles.

```r
ctg <- catalog_select(ctg, method = "flag_processed")
```

**Comment by lucas-johnson** [comment]
Awesome, thanks for implementing this.

**Comment by lucas-johnson** [comment]
Do you have any estimate when 2.2 will be released?

**Comment by Jean-Romain** [comment]
You can already install 2.2 from github with

```r
remotes::install_github("Jean-Romain/lidR", ref = "devel")
```

but I plan to release hopefully on Jan 1st 2020.
