### ISSUE TITLE
Filter a LAS catalog prior to some function

### ISSUE THREAD

**Issue by Myxomycota** [Jean-Romain/lidR#307]
So suggesting I want to do something along the following lines:

```
LAS.cat <- catalog("\somepath\")

f = function(x) { x * 0.125 + 10}

ttops <- lasfilter(LAS.cat, Z<250) %>% tree_detection(lmf(f))
```

In my data set, there are some birds that are present in the data set and giving me false positives in segmentation. `lasfilter()` doesn't appear to handle a catalog object. Is there a best practice I'm missing here?

**Comment by Jean-Romain** [comment]
Yes but I no longer answer to questions on github. Please ask your questions on https://gis.stackexchange.com/ with the tag `lidr`. This way your question and the community's answer will benefit to everybody by being indexed by search engine. Please only report bug on github (or feature request). Thanks.
