### ISSUE TITLE
is.overlapping() is too sensitive

### ISSUE THREAD

**Issue by lucas-johnson** [Jean-Romain/lidR#310]
The `is.overlapping` flag seems too sensitive. In the following case, the total area of overlap in the catalog is less than 1 square mm. It might be better to set a threshold greater than 0, only over which the `is.overlapping()` function would return `TRUE`. I'm not sure what that threshold should be (.01% of total area, or 1 square unit of area), but the current threshold seems too sensitive. 
 
Example:
```r
is.overlapping(ctg)
#> [1] TRUE
spdf <- as.spatial(ctg)
contour <- rgeos::gUnaryUnion(spdf)
actual_area <- contour@polygons[[1]]@area
measured_area <- area(ctg)
actual_area < measured_area
#> [1] TRUE
actual_area
#> [1] 54000000
sprintf("%.10f",actual_area)
#> [1] "54000000.0000000000"
measured_area
#> [1] 54000000
sprintf("%.10f",measured_area)
#> [1] "54000000.0000712425"
measured_area - actual_area
#> [1] 0.0001000017
ctg
#> class       : LAScatalog
#> extent      : 366000 , 372000 , 4717500 , 4726500 (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=utm +zone=18 +ellps=GRS80 +units=m +vunits=m +no_defs 
#> area        : 54 km²
#> points      : 311.79 million points
#> density     : 5.8 points/m²
#> num. files  : 24 
```

**Comment by Jean-Romain** [comment]
You are right this should be improve. 

1 square unit threshold seems a reasonable option but I think it will fail if the points are stored in degrees. A percentage is maybe not the best option because it won't detect a duplicated file in a large dataset.

I could also add an argument in `is.overlapping` print/plot a report and show where are the overlaps and how much it is overlapping.

Could you update your issue by updating the values without `round(..., 4)` to see the actual values.

**Comment by Jean-Romain** [comment]
What do you think of a new function `overlaps()`

``` r
overlaps <- function(catalog) {
  spdf <- as.spatial(catalog)
  ii <- rgeos::gIntersects(spdf, byid = TRUE, returnDense = FALSE)
  
  intersections <- vector("list", length(ii))
  
  for (i in 1:length(ii)) {
    k <- ii[[i]]
    k <- k[k != i]
    p <- spdf[k, ]
    q <- spdf[i, ]
    w <- rgeos::gIntersection(q, p)
    w@polygons[[1]]@ID <- as.character(i)
    intersections[[i]] <- w
  }
  
  output <- do.call(rbind, intersections)
  output <- rgeos::gUnaryUnion(output)
  return(output)
}

library(lidR)
#> Le chargement a nécessité le package : raster
#> Le chargement a nécessité le package : sp
par(mfrow=c(1,2))
ctg <- readLAScatalog("~/Documents/ALS data/BCTS/")
#> Be careful, some tiles seem to overlap each other. lidR may return incorrect outputs with edge artifacts when processing this catalog.
over <- overlaps(ctg)

plot(ctg)
plot(over, add = T, col = "red", border="red", lwd = 0.5)

plot(over, add = F, col = "red", border = "red", lwd = 0.5)
```

![](https://i.imgur.com/WiihXVC.png)

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lucas-johnson** [comment]
I have updated my post to display the unrounded areas...

I like the `overlaps(ctg)` function. This would be very helpful for me.

**Comment by Jean-Romain** [comment]
Please share your `LAScatalog` using `saveRDS()` or `dput()`

**Comment by lucas-johnson** [comment]
I'm not sure how you want me to share the catalog. It is quite large. I tried compressing the tiles to `laz` files and zipping them, but the resulting zip file is 1.24 GB which is too big to post here.

**Comment by lucas-johnson** [comment]
[test_ctg.txt](https://github.com/Jean-Romain/lidR/files/4022176/test_ctg.txt)

**Comment by Jean-Romain** [comment]
I don't need your point cloud. I only need the R object that represents the `LAScatalog` which is only few KB. Using `saveRDS` you can write any R object in a binary file. Using `dput` you generate a copy/pastable string that will allow me to reconstruct the R object. Both are correct.

**Comment by lucas-johnson** [comment]
Ok understood. I used `dput` to save the catalog to a `.txt` file:

[test_ctg.txt](https://github.com/Jean-Romain/lidR/files/4022197/test_ctg.txt)

**Comment by Jean-Romain** [comment]
Well, actually a `LAScatalog` is a complex object and its constructor is not properly written. `dput` does not enable me to reconstrut the object. Please use `saveRDS`.

**Comment by lucas-johnson** [comment]
Github doesn't support the `.rds` extension, so I have saved the RDS object as a `.txt` file:
[test_ctg.txt](https://github.com/Jean-Romain/lidR/files/4022221/test_ctg.txt)

**Comment by Jean-Romain** [comment]
Ok I understood your issue. The header is not (strictly) well populated. It gives the extent of the files instead of the the coordinates of the most right/left/top/bottom points. For example `Max X` on the left tile is 367500 and `Min X` on the right is 367500 as well. So the intersection area is 0 and the intersection shape is a line.

It is expected, for example, that `Max X` on the left tile is 367499.99 and `Min X` on the right is 367500.02.

Anyway this should give an intersection area of 0 but we get 0.0001000017 which is likely to be an precision error due to how computers work.

**Comment by Jean-Romain** [comment]
I edited the function `overlaps` above. I will fix that in `is.overlapping`.

**Comment by lucas-johnson** [comment]
I'm seeing another edge case in `overlaps` where:
```
w <- rgeos::gIntersection(q, p)
```
results in a `SpatialCollections` object containing 2 lines and 1 point. 

w:
```
w
class       : SpatialCollections 
features    : 1 
extent      : 363011.3, 364500, 4720500, 4722000  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=18 +ellps=GRS80 +units=m +vunits=m +no_defs 
```

p:
```
plot(p)
```
![image](https://user-images.githubusercontent.com/10555272/71771061-5d99f680-2f03-11ea-9c48-0550a3f46a3c.png)

q:
```
plot(q, add=TRUE, col="red")
```
![image](https://user-images.githubusercontent.com/10555272/71771066-75717a80-2f03-11ea-8519-9a075e6db8ed.png)

Overlaps:
```
plot(w@lineobj, col="blue")
plot(w@pointobj, col="blue", add=TRUE)
```
![image](https://user-images.githubusercontent.com/10555272/71771092-bec1ca00-2f03-11ea-85ab-0718b24b1d54.png)



Error Message:
```
 Error in overlaps(catalog) : 
  no slot of name "polygons" for this object of class "SpatialCollections" 
```

Problematic catalog: 
[test2_ctg.txt](https://github.com/Jean-Romain/lidR/files/4022379/test2_ctg.txt)

**Comment by Jean-Romain** [comment]
This one handle this edge case

```r
overlaps <- function(catalog) 
{
  spdf <- as.spatial(catalog)
  ii <- rgeos::gIntersects(spdf, byid = TRUE, returnDense = FALSE)
  
  intersections <- vector("list", length(ii))
  
  for (i in 1:length(ii)) 
  {
    k <- ii[[i]]
    k <- k[k != i]
    
    if (length(k) == 0) next
    
    p <- spdf[k, ]
    q <- spdf[i, ]
    w <- rgeos::gIntersection(q, p)
    
    if (is(w, "SpatialLines")) next
    
    if (is(w, "SpatialCollections")) {
      if (is.null(w@polyobj)) next
      w <- w@polyobj
    }
    
    w@polygons[[1]]@ID <- as.character(i)
    intersections[[i]] <- w
  }
  
  if (all(sapply(intersections, is.null))) {
    empty <- SpatialPolygons(list())
    raster::projection(empty) <- raster::projection(catalog)
    return(empty)
  }
  
  output <- do.call(rbind, intersections)
  output <- rgeos::gUnaryUnion(output)
  return(output)
}
```

**Comment by Jean-Romain** [comment]
In `v2.2.0` (release on jan 6th) I added a small tolerance.
In `v2.3.0` I will add the function `overlaps`
