### ISSUE TITLE
general troubles installing 2.2

### ISSUE THREAD

**Issue by spono** [Jean-Romain/lidR#313]
Ciao JR,
I'm having some weird troubles updating from 2.1.5 to 2.2 on W10.
1. I used `devtools::install_github("Jean-Romain/lidR","master")` and got an invalid install (e.g. "unable to update, rolling back to previous"). Re-trying, it started to give errors like `"there is no package called ‘(digest, rlang, ecc.)’"` but somethings goes wrong with i386 (I can send a copy of the log).
2. I tried then `devel`: same stuff.
3. I updated R from 3.6.1 to 3.6.2: same issues.
4. as a test, CRAN package (2.2.0 ): seems to install almost properly 
5. I wiped out R & Rstudio, cleaned, reinstalled through `devtools` and now 2.2.1 seems to work .

windows-related stuff?

sorry for the messed up message but I personally finished the ideas :)

**Comment by Jean-Romain** [comment]
2.2.0 is on CRAN. Just `install.package("lidR")`. Also for the future `devtools::install_github()` is deprecated. Use `remotes::install_github()` (I know, I didn't update the README)
