### ISSUE TITLE
Error using templated file name

### ISSUE THREAD

**Issue by azh2** [Jean-Romain/lidR#324]
I am getting the following error when trying to use {ORIGINALFILENAME} in the catalog opt_output_file option

`opt_output_files(Tst1) <- "C:/Users/azh2/R/Out_Dir/{ORIGINALFILENAME}_DEM"`

`grid_terrain(las = Tst1, res = 1, algorithm = kriging(model = gstat::vgm(0.59, "Sph", 874), k = 10L),keep_lowest = TRUE)`

`**Error in eval(parse(text = text, keep.source = FALSE), envir) : object 'ORIGINALFILENAME' not found**`

![image](https://user-images.githubusercontent.com/41212282/75731689-2e0a2f00-5ca5-11ea-926b-1580fb1afc5b.png)

**Comment by azh2** [comment]
The others appear to work fine, I am using {ID} now

**Comment by Jean-Romain** [comment]
See https://github.com/Jean-Romain/lidR/issues/271
