### ISSUE TITLE
Function for producing the range for each point

### ISSUE THREAD

**Issue by lucas-johnson** [Jean-Romain/lidR#328]
### Feature Request / Enhancement
It would be very helpful to have a function that can produce the range value for every point. My personal use case is to determine whether or not intensity values need range correction. Range values for each point are necessary to produce a plot like the following (taken from http://www.geogra.uah.es/images/Documentos/emilio/PDF/garcia2010.pdf): 
![image](https://user-images.githubusercontent.com/10555272/77206403-41066700-6acd-11ea-8643-51fbe8f50c9c.png)

**Comment by Jean-Romain** [comment]
New function `get_range()` in v3.0.0 (branch `devel`). This version brings a lot of changes. Please read carefully the [changelog](https://github.com/Jean-Romain/lidR/blob/devel/NEWS.md).
