### ISSUE TITLE
Error when running `grid_terrain()`

### ISSUE THREAD

**Issue by lucas-johnson** [Jean-Romain/lidR#332]
Running `grid_terrain()` on a catalog with the following settings:
```
opt_stop_early(ctg) <- FALSE
opt_chunk_buffer(ctg) <- 100
opt_filter(ctg) <- "-drop_withheld -drop_class 7 18"
opt_output_files(ctg) <- "~/Downloads/dtm/{*}"
opt_progress(ctg) <- FALSE
```
I have also selected some files as buffer only:
![image](https://user-images.githubusercontent.com/10555272/77557171-d28c2500-6e8f-11ea-8056-f46b03367443.png)

I get the following error message:
```
> grid_terrain(ctg, res=1, knnidw(k=5))
The original tiling pattern does not match with the resolution 1. Chunks were extended to avoid partial pixels.
Error in if (all(!process[tile_is_in_bbox])) select <- FALSE else if (sum(tile_is_in_bbox) >  : 
  missing value where TRUE/FALSE needed
```

**Comment by Jean-Romain** [comment]
This is not related to `grid_terrain` but to the function that creates the chunks. Please save your `LAScatalog` with `saveRDS` and share it. This should be enought to reproduce. Please also mention your `lidR` version.

**Comment by lucas-johnson** [comment]
Yeah it seems to be a problem with grid_metrics as well.  I encountered the bug with the `devel` branch (lidR 3.0.0), but have sense reinstalled the current cran distribution (lidR 2.2.3), and have the same issue. 

[ctg_chunk_bug.rds](https://github.com/Jean-Romain/lidR/files/4382046/ctg_chunk_bug.rds)

**Comment by lucas-johnson** [comment]
Seems to be working in version 2.2.2

**Comment by Jean-Romain** [comment]
Could you confirm if this work or not

```r
lidR:::catalog_makecluster(ctg)
```

Surprisingly it works on my computer

**Comment by lucas-johnson** [comment]
Yes it works in version 2.2.3.

**Comment by lucas-johnson** [comment]
R

**Comment by Jean-Romain** [comment]
Ok I reproduced. It fails with the partial processing only.

```r
library(lidR)
ctg = readRDS("~/Téléchargements/ctg_chunk_bug.rds")
lidR:::catalog_makecluster(ctg, realignment = list(res = 20, start = c(0,0))) # fail

ctg$processed = NULL
lidR:::catalog_makecluster(ctg, realignment = list(res = 20, start = c(0,0))) # ok
```

**Comment by Jean-Romain** [comment]
Fixed

**Comment by lucas-johnson** [comment]
Thanks so much!
