### ISSUE TITLE
clip_roi breaks for a Simple Feature if geometry column isn't named "geometry" in lidRv3.0.0

### ISSUE THREAD

**Issue by mikoontz** [Jean-Romain/lidR#333]
Hello!

This line is the culprit: [https://github.com/Jean-Romain/lidR/blob/devel/R/clip_roi.R#L388](https://github.com/Jean-Romain/lidR/blob/devel/R/clip_roi.R#L388) for a LAS data type and this line for the LAScatalog: [https://github.com/Jean-Romain/lidR/blob/devel/R/clip_roi.R#L408](https://github.com/Jean-Romain/lidR/blob/devel/R/clip_roi.R#L408)

This can be fixed by using sf::st_geometry() in place of sf$geometry

PR on its way!

**Comment by Jean-Romain** [comment]
I'm closing. Discussion continue in #334.
