### ISSUE TITLE
Reproject (horizontal and vertical)?

### ISSUE THREAD

**Issue by jgrn307** [Jean-Romain/lidR#340]
I was curious if there is a way to convert LAS points between horizontal and vertical datums?  We've got some data that is NAD83 and needs to be tweaked to NAVD88.

**Comment by Jean-Romain** [comment]
I don't think so. The tool for projection available is only a wrapper around `sp::spTransform`. It reprojects xy leaving z unmodified. If `sp` is capable of such transformation I guess lidR too. But anyway I really do not recommend to use R for that. Use `las2las` from `LAStools` instead.
