### ISSUE TITLE
I have a mistake about writeLAS

### ISSUE THREAD

**Issue by LiuQW-YNnormal** [Jean-Romain/lidR#341]
when I used lastrees, the las data can't wirten to a new file.
The code is 

```r
library(lidR)
las1 <- readLAS("D:/testpoint/project.las")
las <- lastrees(las1, li2012(R = 2,speed_up = 5))
plot(las,color='treeID')
writeLAS(las,"D:/testpoint/project1.las")
```
or 

```r
library(lidR)
las1 <- readLAS("D:/testpoint/project.las",select="xyz")
writeLAS(las1,"D:/testpoint/project1.las")
```
they all error 

```
Invalid header: X scale factors should be factor ten of 0.1 or 0.5 or 0.25 not 9.8699e-09**
```

**Comment by Jean-Romain** [comment]
You also have a similar warning at read time right ? See

- https://gis.stackexchange.com/questions/333324/rescaling-las-file-with-lidr-package-in-r
- https://gis.stackexchange.com/questions/360247/rescaling-and-reoffsetting-a-photogrammetry-point-cloud-with-lidr

**Comment by LiuQW-YNnormal** [comment]
Thanks for you very mach
