### ISSUE TITLE
CRS definition discards datum

### ISSUE THREAD

**Issue by MullerMitro** [Jean-Romain/lidR#359]
Hi

I have downloaded .laz files from Finnish National Land Survey. They are all saved with EPSG:3067 - ETRS89 / TM35FIN(E,N)  -coordinate reference (https://tiedostopalvelu.maanmittauslaitos.fi/tp/kartta?lang=en). I try to determine the CRS information for these files without success.

```
#Read file
lasFile = readLAS("file_folder_parth")
#determine CRS
epsg(lasFile) = 3067
#OR
projection(lasFile) = CRS("+init=epsg:3067")
```

Both methods return message

```
Warning message:
In showSRID(SRS_string, format = "PROJ", multiline = "NO") :
  Discarded datum European_Terrestrial_Reference_System_1989 in CRS definition
```

I processed canopy height raster with grid_canopy() -function, and overlaid resulting raster with other map layers in QGIS. 
Clear spatial shifts were observable. Is there a way around this?

**Comment by Jean-Romain** [comment]
See https://cran.r-project.org/web/packages/rgdal/vignettes/PROJ6_GDAL3.html. 

I don't have control of CRS related stuff and actually I only have a very partial understanding of CRS. What I can tell you is that `grid_something()` functions don't use the CRS they only copy the CRS of the `LAS` object to the `Raster` object. Your raster are perfectly aligned with the point cloud meaning that either:

- the point cloud is misaligned
- the misalignment occurs when writing the raster
- the epsg code is not the good one
- other

In any case it cannot come from `lidR` that only processes the raw coordinates of the points without doing any CRS related stuff except the interpretation of the epsg code read in the file (if any) exactly as you did `sp::CRS("+init=epsg:3067")`

Maybe give me a link to one file + a reproducible example so I can see what we are talking about
