### ISSUE TITLE
Tree-crown delineation on LAS Catalog

### ISSUE THREAD

**Issue by azh2** [Jean-Romain/lidR#370]
Are there any examples of tree crown delineation being applied on an lascatalog?

**Comment by Jean-Romain** [comment]
Chapter [14](https://jean-romain.github.io/lidRbook/engine.html) sections [14.11](https://jean-romain.github.io/lidRbook/engine.html#engine-itd) and [14.12](https://jean-romain.github.io/lidRbook/engine.html#engine-its)
