### ISSUE TITLE
las_reoffset: small bug and a few typos

### ISSUE THREAD

**Issue by Lenostatos** [Jean-Romain/lidR#371]
Dear lidR developers,

I think I've spotted a small bug in the code of the las_reoffset function: In [line 70](https://github.com/Jean-Romain/lidR/blob/838ba8f7dfa1b076d876e403c9c78cf0c72ef943/R/las_tools.R#L70) the maximum Z value of the public header block is fetched with a lower-case `z` instead of an upper-case one, i.e. the code goes
`las@header@PHB[["Max z"]]` (which returns `NULL`) instead of
`las@header@PHB[["Max Z"]]`.
As far as I can tell this would only be a problem in very rare edge cases, though.

Regarding the documentation of the las_rescale and las_reoffset functions:

I think it should go
"This function _modifies_ the header and _recomputes_ the coordinates. Coordinates might be moved by few tenth of _a millimeter_ or few millimeters depending _on_ the accuracy imposed by the user."
instead of
"This function modify the header and recompute the coordinates. Coordinates might be moved by few tenth of millimeters or few millimeters depending of the accuracy imposed by the user.".

_Disclaimer:_ I am confident in my English skills in this case but English is not my mother tongue, so please ignore anything that looks wrong to you.

Kind Regards,
Leon

**Comment by Jean-Romain** [comment]
Thank you for reporting. It is fixed now. I guess this bug has actually no effect because it was on Z. On XY it may have been critical. I also fixed the doc. Thanks for the corrections
