### ISSUE TITLE
Add voxel resolution to lasmetrics3d class?

### ISSUE THREAD

**Issue by jgrn307** [Jean-Romain/lidR#376]
Once of the things that would be helpful is to preserve the voxel metadata in the output of voxel_metrics, specifically the voxel size used in the calculations -- a lot of subsequent analysis I'm doing on the voxel output requires knowledge of the initial voxel size.  Is this something you could add as a slot to the lasmetrics3d class?

**Comment by Jean-Romain** [comment]
My first answer was *yes sure*. Then, I looked at the source code and found that it already exists

https://github.com/Jean-Romain/lidR/blob/37b81e713270c0697f5b42c439518502b4b06693/R/voxel_metrics.R#L95

It is an attribute of the object so you can access it with `attr(metrics, "res")`. But it is indeed missing in the documentation.
