### ISSUE TITLE
Unable to retrieve treeID after segmentation

### ISSUE THREAD

**Issue by Elephant-C** [Jean-Romain/lidR#384]
Hi there,

A quite useful and stable solution for forest lidar data processing and analysis. However, I encountered a problem that treeID feature can not be retrieved after implementing Dalponte2016 chm-based segmentation method (please see figure1). The segmentation results can correctly show in multiple colors by using **_plot(las_res, bg = "white", size = 2, color = "treeID")_**, but These treeIDs are actually Not Available(NA), and I cannot export the treeIDs in both las/laz and .csv formats.

Could you please tell me how to fix this?
Thanks a lot.

**figure1**
<img width="656" alt="111" src="https://user-images.githubusercontent.com/29450176/96392139-b9611200-11ed-11eb-969f-82b8b6de9c64.png">

Best regards,
Yujie Cao

**Comment by Jean-Romain** [comment]
Sounds like a question. This is a bug tracker. Please ask questions on https://gis.stackexchange.com/questions/tagged/lidr with the tag `lidr` and add a **reproducible** example. As is, there is no way I can hep you.,
