### ISSUE TITLE
Clarification on the PitFree Algorithm

### ISSUE THREAD

**Issue by azh3** [Jean-Romain/lidR#385]
Khosravipour et al, (2014) only characterize 2 thresholds for their implementation of the Pit-Free algorithm.

1. "The height thresholds, which define the set of partial CHMs, and 
2. The rasterization threshold, which includes only those triangles with edge lengths below a particular value"

The height thresholds are passed to 'thresholds' while the max_edge= c( _ , _ ) argument takes 2 values, 

"The first number is the value for the classical triangulation (threshold = 0, see also dsmtin), the second number is the value for the pit-free algorithm (for thresholds > 0). If max_edge = 0 no trimming is done (see examples). 

So I am assuming the first threshold is for CHM00 while the second threshold is the triangulation threshold for the generation of all subsequent CHMs (2 meters and above)?

Thank you for clarifying this!

.

**Comment by Jean-Romain** [comment]
Exact. The first number is actually useful only for areas that are not convex. Otherwise just input 0.
