### ISSUE TITLE
Aligning grid metric raster cells between multiple ALS missions for a given area in lidR

### ISSUE THREAD

**Issue by M-Woods61** [Jean-Romain/lidR#387]
Excuse me if I am posting this in the wrong place.

I have 3 different ALS datasets from various years covering the same general area. However, each ALS data has a different extent from each other. 

I would like to make sure my raster grid for my predictors align with each other (20x20m)  - However, since the extents of the ALS data are different for each mission and I assume that this will cause me alignment issues unless I pre-process some aspect of the project. 

Is there an efficient way of doing this in lidR?  Would you recommend clipping the lascatalog as a first step? Any thoughts/advice would be appreciated.

Thanks.
Murray

**Comment by Jean-Romain** [comment]
No, if the point clouds are all in the same reference coordinate system `grid_metrics` compute the same cells for each datase. The grid is fixed but can be shifted manually if needed.

For next questions please ask on https://gis.stackexchange.com/questions/tagged/lidr with the tag `lidr`.
