### ISSUE TITLE
Using a large LAScatalog in find_trees

### ISSUE THREAD

**Issue by trevor-hobbs** [Jean-Romain/lidR#394]
Currently, I’m testing a batch processing workflow on a small area (16 tiles, 1250x1250 ft in size).  I’ve noticed some interesting behavior when using find_trees… Specifically, when using a LASCatalog object as an input argument, the find_trees will output a shapefile of tree point locations to disk, while R stores a value to represent it (comprised of a list of the shapefiles written to disc), rather than a spatial points data frame.  This makes it tricky to use in subsequent batch processing tools (such as segment_trees), because the value is of type = character and not a spatial points data frame, which is what most of the segmentation methods require.

My workaround has been to pass the canopy height model as a rasterLayer as input into find_trees (rather than using the LASCatalog as input).  This workaround seems to store the tree tops as a spatial points data frame as expected in my small testing scenario (with 99,545 trees).  However, as I move toward processing the whole catalog (1668 tiles), I can see this data frame getting quite large (10-12 million elements)… Potentially being too large to store in memory.

**Two questions:**

1) Is the above behavior for find_trees expected when processing large areas with a LAScatalog object (and why?)?

2) Is there any practical limit to the number of elements in a spatial points data frame outside of memory issues specific to the computer?

Thank you!

**Comment by Jean-Romain** [comment]
I think section 11 of chapter 14 will help you

https://jean-romain.github.io/lidRbook/engine.html#engine-itd

If you have any question about the lidR package do not hesitate to ask on https://gis.stackexchange.com/questions/tagged/lidr with the tag `lidr`. Github is used as bug tracker not as a platform to answer users's questions.

Thank you
