### ISSUE TITLE
Number of threads 

### ISSUE THREAD

**Issue by justbennet** [Jean-Romain/lidR#410]
It appears from some testing that if I `export OMP_NUM_THREADS=4`, that the `normalize_height()` and `grid_canopy()` functions actually use only 2 threads.

I am running `lidR` on a cluster on which the number of CPUs is part of the job request.  I was using the variable the job manager sets to set the value of `OMP_NUM_THREADS` and was surprised that `lidR` appeared to be using only half of them.  If I set it to `$((SLURM_NPROCS*2))` I seem to get all of the CPUs assigned to the job.

Is this intended behavior?  

Thanks

**Comment by Jean-Romain** [comment]
By default `lidR` uses half of the core. This is documented in `?lidR-parallelism`

> By default lidR uses half of your cores but you can control this with `set_lidr_threads()`.

Use

```r
set_lidr_threads(0)
```

See `?set_lidr_threads()`
