### ISSUE TITLE
Suggested modification of the parameter max_cr_factor thresholds in silva2016

### ISSUE THREAD

**Issue by sanmaral** [Jean-Romain/lidR#417]
We have frequently used the silva2016 method for segmenting trees, with generally very satisfactory results. However, we encounter problems in certain forest types (dehesas, and other Mediterranean oak forests), where the diameter of the crown is often greater than the height of the tree. We have tried modifying the silva2016 function to allow us to increase the value of the `max_cr_factor` parameter up to 2, and this modification solved our problem. At the moment the argument is limited to take values between 0 and 1. Based on our experience, we propose to increase this range to 2 in order to be able to work satisfactorily in a wider range of forest types.

**Comment by Jean-Romain** [comment]
Thanks, `max_cr_factor` is now allowed to be in [0, +∞[
