### ISSUE TITLE
LAI

### ISSUE THREAD

**Issue by Saadi4469** [Jean-Romain/lidR#432]
Hello,

Can this package be used to calculate LAI? If yes, what functions can help in calculating it? If no, then what packages (like 'canopylazR' and 'leafR' in R are preferred for determining LAI?

Thank you,

**Comment by Jean-Romain** [comment]
There is a LAD function. Yet computing the LAI from a point cloud require to define how to do it. Without definition I can't answer. The LAD is based on a peer-reviewed publication. If you want to ask broad questions you are better to ask on forum where there are many people to answers. Here it is the bug tracker of the lidR package.
