### ISSUE TITLE
find trees manual feature request

### ISSUE THREAD

**Issue by Saadi4469** [Jean-Romain/lidR#445]
Hello,

Can you please add a feature if possible to allow the user to flag multiple tree tops next to each other by creating a single selection window while using the middle mouse button?  Because right now even if I create a bigger selection window, only one tree top gets removed instead of removing all the tree tops in that window.

Thank you,

**Comment by Jean-Romain** [comment]
This was a very pertinent request so I did it. Thank you.

**Comment by Saadi4469** [comment]
So I should again update the package from github, right?

**Comment by Jean-Romain** [comment]
yes
