### ISSUE TITLE
Typo in stdmetrics_i, 

### ISSUE THREAD

**Issue by jmmonnet** [Jean-Romain/lidR#49]
I have lidR 1.1.0 installed, there is a typo error in function stdmetrics_i. One should read 
> ipcumzq70 = sum(i[z <= zq[4]])/itot * 100

instead of

> ipcumzq70 = sum(i[z <= zq[3]])/itot * 100

Thank you for the very useful package.

**Comment by Jean-Romain** [comment]
Exact, thank you for reporting this bug. You can download lidR 1.2.0 from github
