### ISSUE TITLE
Missing argument in function stdmetrics

### ISSUE THREAD

**Issue by jmmonnet** [Jean-Romain/lidR#50]
Hi I use lidR 1.10, and noticed that the cumulated intensity below height percentiles are different if you obtain them with stdmetrics or directly with stdmetrics_i. Maybe it is because of missing z argument in stdmetrics:

> I = stdmetrics_i(i, z, class, rn)

instead of

> I = stdmetrics_i(i, class, rn)

**Comment by Jean-Romain** [comment]
Hi, they are more than different.  The one from `stdmetric` is wrong. Thank you for reporting this issue. Bug solved in lidR 1.2.0 available on github

I'll make more unit tests for these features... I wrote them too quickly from an old script...
