### ISSUE TITLE
lasground?

### ISSUE THREAD

**Issue by tlrm-c** [Jean-Romain/lidR#57]
what about this function? Your are using this in your example 'Tree-segmentation-from-A-to-Z'.
But it's not working and there is no description in the lidR.pdf
Would be nice to have the  progressive morphological filter (same as in PDAL: https://www.pdal.io/stages/filters.pmf.html#filters-pmf ?)
thanks a lot

**Comment by Jean-Romain** [comment]
The wiki pages are up to date with the development version on github. `lasground` is available since 1.2.0 (on CRAN within few days) and *is* the progressive morphological filter from PDAL (or PCL since its the same)

**Comment by tlrm-c** [comment]
oh, ok. Im pretty new in R and on github - thank you for helping!
