### ISSUE TITLE
Error in lasground

### ISSUE THREAD

**Issue by karnayogendra** [Jean-Romain/lidR#58]
Hi,  I found following error while using lasground for Tree-segmentation-from-A-to-Z exercise from the following link: https://github.com/Jean-Romain/lidR/wiki/Tree-segmentation-from-A-to-Z.

Error in .Call("lidR_MorphologicalOpening", PACKAGE = "lidR", X, Y, Z,  : 
  "lidR_MorphologicalOpening" not available for .Call() for package "lidR"
Please advise me how to solve it.

Thanks and Regards,
Yogendra

**Comment by Jean-Romain** [comment]
Hi,

This not the first time somebody report a strange problem like that. It cannot be a problem with the code. I mean, all the examples of code from the doc are tested by the CRAN (and I) and also other tests are ran. If a function was missing (or was not callable) the package would be rejected. Therefore I guess it's a problem with the user installation. So try to uninstall and reinstall the package. If the problem persist we will investigate further.

JR

**Comment by Jean-Romain** [comment]
See also #43
