### ISSUE TITLE
catalog reading .lasx files

### ISSUE THREAD

**Issue by pdbentley** [Jean-Romain/lidR#6]
files = list.files(folder, full.names = T, pattern = "\\.las|.laz$", ...)

**Comment by pdbentley** [comment]
Hey JR, 

ill add a couple of other small things i've come across. 

firstly, thanks for updating the list.files. it works, however i also have .lasx files (its an ESRI stats file). i had a quick look but could find a simple way to update the pattern recognition bit. i use grep alot, but not sure if it works here.

**Comment by Jean-Romain** [comment]
Hi, 

Not sure to understand the question. You mean that lasx files are recognize in the following pattern `\\.las|.laz$` and you want the pattern to do not take into account these files keeping only las and laz?

If yes it easy I'll do that.

**Comment by Jean-Romain** [comment]
Done is `develop` branch.

**Comment by pdbentley** [comment]
great.  thanks. that will stop it falling over from pesky extension names.
