### ISSUE TITLE
Bug in catalog_makecluster

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/lidR#83]
This code creates a weird pattern of clusters. This is not a bug because internally the code handle properly empty cluster but it should be fixed.

```r
catalog_options(multicore = 1, tiling_size = 160, buffer = 0)

file <- system.file("extdata", "Megaplot.laz", package="lidR")
ctg = catalog(file)

m1 = grid_metrics(ctg, .stdmetrics, 20)
```

**Comment by Jean-Romain** [comment]
The example in `catalog_apply` is bugged because of the error in the clustering

**Comment by spono** [comment]
hi JR,
using `catalog_apply` from `master` on my data, almost the same procedure (`multicore=3, tiling_size=100, buffer=0`) gives me `Progress: 100%` but in the task manager the 3 processes are still open, one of which running at 25-40% and the other two at 0%.
may it be the same bug?

**Comment by Jean-Romain** [comment]
No it isn't ! If your problem persists is might be a problem with the `future` package imo. I can have a look but so far I didn't see any issue like that.
