### ISSUE TITLE
Error in UseMethod ("grid_canopy",x)

### ISSUE THREAD

**Issue by mkieser** [Jean-Romain/lidR#94]
> las = lasnormalize(las, method = "kriging")
[using universal kriging]
Warning messages:
1: There were 3 duplicated ground points. Some X Y coordinates were repeated but with different Z coordinates. min Z were retained.
2: 15 points below 0 found.
> chm1 = grid_canopy(las, 0.5)
**Error in UseMethod("grid_canopy", x) :
  no applicable method for 'grid_canopy' applied to an object of class "NULL"**
>

**Comment by Jean-Romain** [comment]
From the doc of `lasnormalize`

> The function returns NULL. The LAS object is updated by reference. Z is now the normalized elevation, A new column 'Zref' records the former elevations values. This is a way to save memory avoiding copies of the point cloud. But if copy = TRUE, a new LAS object is returned and the original one is not 

Should be use like in the doc

```r
las = readLAS(...)
lasnormalize(las, ...)
grid_metrics(las, ...)
```
