### ISSUE TITLE
Issue in readLAS with option F without option t

### ISSUE THREAD

**Issue by ovanlier** [Jean-Romain/lidR#96]
Hi JR,

Just an FYI:

Script ran fine, upgraded R and RStudio and now get the following error:

> No 'gpstime' field found. 'flightlineID', cannot be computed from this file. 

The code which returns an error:

```
las = readLAS(LASFile, select = "xyzaF")
```

It does however work without error, albeit with larger space usage in environment, when we keep `gpstime' in 'select = "xyzatF"' as:

```
las = readLAS(LASFile, select = "xyzatF")
```

Just thought you may like to know :)
Olivier

**Comment by Jean-Romain** [comment]
Hi Olivier,

Indeed this is a minor bug. `gpstime` is needed to retrieve the `flightlineID` so if you disable `t` thus `flightlineID` cannot be computed. This is not a major issue but I can easily solve it by forcing the `t` option if `F` is provided. But currently the error message is clear and helpful.

I will balance the pros and the cons.

Thanks for reporting the issue.
