### ISSUE TITLE
Issue with V1.4.0.9 "Error: Incorrect argument 'filter'"

### ISSUE THREAD

**Issue by slpgnt** [Jean-Romain/lidR#97]
Hi JR,

This may be a trivial issue that is unique to me. When running my code with v1.4.0.9 I received an error:
"Error: Incorrect argument 'filter'"
I narrowed it down to the readLAS function. For simplicity I tried loading in the MixedConifer.laz from the extra data attached to the package folder and received the same error. Below is the code used: 

> mixed <- readLAS("C:\\Users\\my_user\\Documents\\R\\win-library\\3.4\\lidR\\extdata\\MixedConifer.laz")
Error: Incorrect argument 'filter

Thank you

**Comment by Jean-Romain** [comment]
Hi,

Are you Wim or Wim's colleague? Somebody wrote me by email about this issue yesterday and today.

This is a weird bug because `readLAS` do works perfectly (this is definitively the most reliable function tested several time per days...). It seems to be related to a bad installation of the package. They solved the issue by reinstalling the package.

Try and tell me.

**Comment by slpgnt** [comment]
Hi,
I am not him nor his colleague, The function works when re-installing the old version of lidR. Installing the v1.4.0.9 package as below did not seem to work. The package appears to have installed correctly, but still gets the error.

library(devtools)
> remove.packages("lidR", lib="~/R/win-library/3.4")
> install_github("Jean-Romain/lidR")
> Reloading installed lidR
    lidR 1.4.0.9000. For help, for the most up-to-date version or to report a bug, visit https://github.com/Jean-Romain/lidR
library(lidR)
> mixed <- readLAS("C:\\Users\\cwear\\OneDrive - KBM Resources Group\\Documents\\R\\win-library\\3.4\\lidR\\extdata\\MixedConifer.laz")
Error: Incorrect argument 'filter'

**Comment by Jean-Romain** [comment]
Which version of `rlas`are you using ? `utils::packageVersion("rlas")`

**Comment by slpgnt** [comment]
Version 1.1.5

On Jan 5, 2018, at 1:10 PM, Jean-Romain Roussel <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of rlasare you using ? utils::packageVersion("rlas")

**Comment by Jean-Romain** [comment]
Ok I reproduced the bug. I remember now. There is an incompatibility between `rlas 1.1.5` and `lidR 1.4.0`. This is why I must update `rlas` first before to release `lidR`. 

Install `rlas 1.1.6` from github.

**Comment by slpgnt** [comment]
Great! Thank you for your help!

On Jan 5, 2018, at 1:17 PM, Jean-Romain Roussel <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I reproduced the bug. I remember now. There is an incompatibility between rlas 1.1.5 and lidR 1.4.0. This is why I must update rlas first before to release lidR.

Install rlas 1.1.6 from github.
